services:
  c:
    build:
      context: ./c
    environment:
      - library_file=/usr/lib/llvm-11/lib/libclang.so.1
  python:
    build:
      context: ./python
  proxy:
    build:
      context: ./proxy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000
  javascript:
    build:
      context: ./javascript
    ports:
      - 3000:3000
